import { Provider, ServiceInfo, ServiceType, DogSize } from './types';

export const SERVICES: ServiceInfo[] = [
  {
    id: 'boarding',
    label: 'דוגסיטר',
    icon: '🏠',
    description: 'שמירה אישית בבית של הדוגסיטר',
    priceLabel: '/ לילה',
  },
  {
    id: 'sitting',
    label: 'האוסיטינג',
    icon: '🛋️',
    description: 'שמירה בבית שלכם',
    priceLabel: '/ ביקור',
  },
  {
    id: 'walking',
    label: 'דוגווקר',
    icon: '🦮',
    description: 'טיולים עם דוגווקר מנוסה',
    priceLabel: '/ טיול',
  },
  {
    id: 'daycare',
    label: 'פנסיון',
    icon: '🏡',
    description: 'פנסיון לכלבים',
    priceLabel: '/ יום',
  },
  {
    id: 'grooming',
    label: 'טיפוח',
    icon: '✂️',
    description: 'תספורת, אמבטיה ועוד',
    priceLabel: '/ טיפול',
  },
  {
    id: 'training',
    label: 'אילוף',
    icon: '🎯',
    description: 'מאלפים בשיטות חיוביות',
    priceLabel: '/ שיעור',
  },
  {
    id: 'vet',
    label: 'וטרינר',
    icon: '🏥',
    description: 'מרפאות וטרינריות',
    priceLabel: '/ ביקור',
  },
  {
    id: 'taxi',
    label: 'הסעות',
    icon: '🚗',
    description: 'הסעות בטוחות לחיות',
    priceLabel: '/ נסיעה',
  },
];

export const CITIES: string[] = [
  'תל אביב',
  'ירושלים',
  'חיפה',
  'ראשון לציון',
  'פתח תקווה',
  'אשדוד',
  'נתניה',
  'באר שבע',
  'חולון',
  'רמת גן',
  'גבעתיים',
  'הרצליה',
  'רעננה',
  'גבעת שמואל',
  'בני ברק',
  'אשקלון',
  'בת ים',
  'רחובות',
  'כפר סבא',
  'מודיעין',
  'לוד',
  'רמלה',
  'הוד השרון',
  'קריית גת',
  'עכו',
  'אילת',
  'נצרת',
  'טבריה',
  'צפת',
  'קריית שמונה',
  'אור יהודה',
  'יהוד',
  'אלעד',
  'ראש העין',
  'קריית אונו',
  'גן יבנה',
  'יבנה',
  'נס ציונה',
  'רמת השרון',
  'כפר שמריהו',
  'סביון',
  'מזכרת בתיה',
  'גדרה',
  'זכרון יעקב',
  'עתלית',
  'טירת כרמל',
  'קריית ביאליק',
  'קריית ים',
  'קריית מוצקין',
  'קריית אתא',
  'נהריה',
  'עפולה',
  'בית שאן',
  'אריאל',
  'מעלה אדומים',
  'ביתר עילית',
  'בית שמש',
  'קרני שומרון',
];

export const DOG_SIZE_LABELS: Record<DogSize, string> = {
  tiny: 'זעיר (עד 5 ק"ג)',
  small: 'קטן (5-10 ק"ג)',
  medium: 'בינוני (10-25 ק"ג)',
  large: 'גדול (25-45 ק"ג)',
  giant: 'ענק (45+ ק"ג)',
};

export const PROVIDERS: Provider[] = [
  {
    id: 'michal-levi',
    name: 'מיכל לוי',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&auto=format&fit=crop&q=80',
    city: 'תל אביב',
    neighborhood: 'פלורנטין',
    rating: 4.97,
    reviewCount: 124,
    pricePerNight: 180,
    services: ['boarding', 'daycare', 'sitting'],
    verified: true,
    responseTime: 'תוך שעה',
    repeatCustomers: 89,
    yearsExperience: 5,
    bio: 'שלום! אני מיכל, אוהבת כלבים מושבעת עם ניסיון של 5 שנים בטיפול בכלבים מכל הגזעים והגדלים. הבית שלי מרווח עם חצר גדולה בפלורנטין, ואני מקפידה על אווירה חמה ואישית לכל כלב שמגיע אליי. הכלב שלכם יקבל אהבה, טיפול ותשומת לב מלאה כאילו הוא בבית שלו. יש לי ניסיון עם גורים, כלבים מבוגרים, וכלבים עם צרכים מיוחדים.',
    images: [
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&auto=format&fit=crop&q=80',
    ],
    dogSizes: ['tiny', 'small', 'medium', 'large'],
    homeEnvironment: ['חצר פרטית', 'ללא חתולים', 'ללא ילדים קטנים', 'כלב ביתי אחד'],
    available: true,
    whatsapp: '972501234567',
    featured: true,
    distance: '1.2 ק"מ',
    reviews: [
      {
        id: 'r1',
        authorName: 'דנה כהן',
        authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
        dogName: 'בוני',
        rating: 5,
        text: 'מיכל היא פשוט מדהימה! בוני חזר הביתה שמח ורגוע, ברור שהיה אצלה מעולה. קיבלנו עדכונים ותמונות לאורך כל היום, מה שנתן לנו שקט נפשי מלא. ממליצה בחום!',
        date: '2025-03-15',
        service: 'לינה',
      },
      {
        id: 'r2',
        authorName: 'יובל שפירא',
        authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
        dogName: 'לונה',
        rating: 5,
        text: 'שלחנו את לונה למיכל לשבוע שלם ולא יכולנו להיות שמחים יותר. הבית נקי, מסודר ומחמם לב. מיכל מקצועית, אמינה ואוהבת כלבים אמיתית. בהחלט נחזור!',
        date: '2025-02-28',
        service: 'לינה',
      },
      {
        id: 'r3',
        authorName: 'אורית לוי',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        dogName: 'מקס',
        rating: 5,
        text: 'מעון היום אצל מיכל הוא פשוט הדבר הכי טוב שעשיתי לכלב שלי. מקס מגיע בבוקר נרגש ואנרגטי וחוזר הביתה עייף ומאושר. מיכל שולחת תמונות ווידאו כל הזמן.',
        date: '2025-01-20',
        service: 'מעון יום',
      },
      {
        id: 'r4',
        authorName: 'תמר גרין',
        authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
        dogName: 'צ\'אנס',
        rating: 5,
        text: 'מיכל טיפלה ב-Chance בזמן שהיינו בחו"ל. תקשורת מעולה, עדכונים שוטפים, ובעלת עיניים חדות לכל שינוי בהתנהגות. חזרנו לכלב מאושר ושלם. תודה מיכל!',
        date: '2024-12-05',
        service: 'לינה',
      },
    ],
  },
  {
    id: 'yossi-cohen',
    name: 'יוסי כהן',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    city: 'הרצליה',
    neighborhood: 'הרצליה פיתוח',
    rating: 4.92,
    reviewCount: 87,
    pricePerNight: 220,
    services: ['boarding', 'sitting'],
    verified: true,
    responseTime: 'תוך שעתיים',
    repeatCustomers: 76,
    yearsExperience: 7,
    bio: 'יוסי כאן! אני מטפל בכלבים כבר 7 שנים ויש לי ניסיון עשיר עם גזעים גדולים ובינוניים. גר בבית פרטי עם חצר מגודרת ומאובטחת בהרצליה פיתוח. אני מאמין שכל כלב מגיע לאהבה, עקביות וסביבה בטוחה. אני בעל גולדן רטריבר בשם קוקו שתמיד שמח לקבל חברים חדשים.',
    images: [
      'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=800&auto=format&fit=crop&q=80',
    ],
    dogSizes: ['small', 'medium', 'large', 'giant'],
    homeEnvironment: ['בית פרטי', 'חצר מגודרת', 'כלב ביתי (גולדן)', 'ידידותי לילדים'],
    available: true,
    whatsapp: '972502345678',
    featured: true,
    distance: '8.5 ק"מ',
    reviews: [
      {
        id: 'r5',
        authorName: 'שיר אביב',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        dogName: 'רוקי',
        rating: 5,
        text: 'יוסי מקצועי ואמין להפליא. רוקי, הרוטוויילר שלנו, תמיד קיבל יחס מיוחד ואוהב. החצר מאובטחת ומושלמת לכלבים גדולים. ממליצה בחום!',
        date: '2025-03-10',
        service: 'לינה',
      },
      {
        id: 'r6',
        authorName: 'אלי ברנר',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        dogName: 'גולדי',
        rating: 5,
        text: 'גולדי נהנה מאוד אצל יוסי! קוקו, הכלב שלו, הפך להיות חבר הכי טוב. יוסי שלח תמונות ועדכונים כל יום. שירות מעל ומעבר!',
        date: '2025-02-14',
        service: 'לינה',
      },
      {
        id: 'r7',
        authorName: 'מיה רוזן',
        authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
        dogName: 'פאקו',
        rating: 4,
        text: 'חוויה מצוינת בסך הכל. יוסי מקצועי ואכפתי. פאקו חזר שמח ורגוע. היחידה שהייתי יכולה להוסיף זה יותר תמונות במהלך השהייה.',
        date: '2025-01-08',
        service: 'שמירה',
      },
    ],
  },
  {
    id: 'noa-sharon',
    name: 'נועה שרון',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    city: 'רמת גן',
    neighborhood: 'נווה עופר',
    rating: 4.89,
    reviewCount: 201,
    pricePerNight: 90,
    services: ['walking', 'daycare'],
    verified: true,
    responseTime: 'תוך 30 דקות',
    repeatCustomers: 93,
    yearsExperience: 4,
    bio: 'היי! אני נועה, מטיילת כלבים מוסמכת עם 4 שנות ניסיון. אני מאמינה שכל כלב צריך פעילות גופנית מספקת ועשרה מנטלית מדי יום. הטיולים שלי הם תמיד 45-60 דקות, בפארקים ובטבע, עם תשומת לב אישית לכל כלב. מקסימום 3 כלבים בטיול אחד.',
    images: [
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1537151625747-768eb2e1aef5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=800&auto=format&fit=crop&q=80',
    ],
    dogSizes: ['tiny', 'small', 'medium'],
    homeEnvironment: ['דירה', 'ללא חיות מחמד אחרות', 'שכונה שקטה', 'קרוב לפארק'],
    available: true,
    whatsapp: '972503456789',
    featured: true,
    distance: '3.1 ק"מ',
    reviews: [
      {
        id: 'r8',
        authorName: 'ליאת מור',
        authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
        dogName: 'ביסלי',
        rating: 5,
        text: 'נועה היא מטיילת כלבים מהטובות שפגשתי! ביסלי ממש אוהב את הטיולים עמה. היא תמיד בזמן, שולחת תמונות וסרטונים, ומגיעה עם שקיות, מים וחטיפים. 10/10!',
        date: '2025-03-20',
        service: 'טיול',
      },
      {
        id: 'r9',
        authorName: 'רון ספיר',
        authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
        dogName: 'טוטו',
        rating: 5,
        text: 'נועה מטיילת עם טוטו כבר חצי שנה. הכלב מחכה לה כל בוקר ליד הדלת. מקצועית, אמינה ואוהבת כלבים אמיתית. ממליץ בחום!',
        date: '2025-02-25',
        service: 'טיול',
      },
      {
        id: 'r10',
        authorName: 'כרמית בן דוד',
        authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
        dogName: 'פיפי',
        rating: 5,
        text: 'המעון יום של נועה הוא ברכה לאמהות עובדות! פיפי חוזרת מאושרת ועייפה בצורה הכי טובה שיש. נועה מסורה ואחראית. ממליצה מאוד!',
        date: '2025-01-15',
        service: 'מעון יום',
      },
      {
        id: 'r11',
        authorName: 'גבריאל לוי',
        authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80',
        dogName: 'ארתור',
        rating: 4,
        text: 'נועה מצוינת! ארתור אוהב אותה מאוד. הטיולים ארוכים ומספקים. לפעמים קצת קשה לתאם שעות אבל בסך הכל שירות מעולה.',
        date: '2024-12-18',
        service: 'טיול',
      },
    ],
  },
  {
    id: 'avi-goldberg',
    name: 'אבי גולדברג',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    city: 'גבעתיים',
    neighborhood: 'קרית קרינגי',
    rating: 5.0,
    reviewCount: 63,
    pricePerNight: 350,
    services: ['training'],
    verified: true,
    responseTime: 'תוך שעה',
    repeatCustomers: 82,
    yearsExperience: 12,
    bio: 'שלום, אני אבי – מאלף כלבים מוסמך בשיטת חיזוק חיובי עם 12 שנות ניסיון. עבדתי עם מאות כלבים מגזעים שונים, כולל כלבים עם בעיות התנהגות מורכבות. הגישה שלי מבוססת על מדע, סבלנות ואהבה. אני מציע שיעורים פרטיים בביתכם או בסטודיו שלי בגבעתיים. תוצאות מובטחות.',
    images: [
      'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&auto=format&fit=crop&q=80',
    ],
    dogSizes: ['tiny', 'small', 'medium', 'large', 'giant'],
    homeEnvironment: ['סטודיו מקצועי', 'שטח פתוח', 'ציוד אילוף מלא', 'שיעורים בביתכם'],
    available: true,
    whatsapp: '972504567890',
    featured: true,
    distance: '2.8 ק"מ',
    reviews: [
      {
        id: 'r12',
        authorName: 'נטע שרון',
        authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
        dogName: 'בארון',
        rating: 5,
        text: 'אבי הוא פשוט קוסם! הכלב שלנו היה עם בעיות קשות של תוקפנות ואבי שינה אותו תוך 4 שיעורים. מקצועי ברמה הגבוהה ביותר. תודה אבי!',
        date: '2025-03-18',
        service: 'אילוף',
      },
      {
        id: 'r13',
        authorName: 'משה כץ',
        authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
        dogName: 'מאפין',
        rating: 5,
        text: 'לקחנו את מאפין לאילוף עם אבי אחרי שניסינו כל מיני מאלפים. אבי הוא הטוב ביותר. הכלב שלנו ממש שונה עכשיו – מציית, רגוע ומאושר.',
        date: '2025-02-20',
        service: 'אילוף',
      },
      {
        id: 'r14',
        authorName: 'ענת פרץ',
        authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
        dogName: 'ג\'ינג\'ר',
        rating: 5,
        text: 'אבי לימד את ג\'ינג\'ר פקודות בסיסיות ואפילו פקודות מורכבות. השיטה שלו נעימה ויעילה, ללא כפייה. ממליצה לכל בעל כלב!',
        date: '2025-01-30',
        service: 'אילוף',
      },
    ],
  },
  {
    id: 'rachel-mizrahi',
    name: 'רחל מזרחי',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    city: 'חיפה',
    neighborhood: 'כרמל מזרחי',
    rating: 4.95,
    reviewCount: 312,
    pricePerNight: 250,
    services: ['grooming'],
    verified: true,
    responseTime: 'תוך שעה',
    repeatCustomers: 95,
    yearsExperience: 8,
    bio: 'שלום! אני רחל, מטפחת כלבים מוסמכת עם 8 שנות ניסיון. הסלון שלי בכרמל מזרחי מציע שירותי טיפוח מלאים: תספורת, אמבטיה ופן, ניקוי אוזניים, גיזום ציפורניים ועוד. אני עובדת עם מוצרים טבעיים ואורגניים בלבד, ומתחייבת שהכלב שלכם יצא יפה, נקי ומאושר.',
    images: [
      'https://images.unsplash.com/photo-1583511655826-05700d52f4d1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1537151625747-768eb2e1aef5?w=800&auto=format&fit=crop&q=80',
    ],
    dogSizes: ['tiny', 'small', 'medium', 'large'],
    homeEnvironment: ['סלון מקצועי', 'ציוד מתקדם', 'מוצרים אורגניים', 'אווירה נינוחה'],
    available: true,
    whatsapp: '972505678901',
    featured: false,
    distance: '45 ק"מ',
    reviews: [
      {
        id: 'r15',
        authorName: 'יעל סמואל',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        dogName: 'קוקי',
        rating: 5,
        text: 'רחל היא הטובה ביותר! קוקי יוצאת מהסלון שלה כמו כלבה אחרת – יפה, ריחנית ומאושרת. לא מפחדת מהאמבטיה כשהיא אצל רחל. מגיעים כל חודש!',
        date: '2025-03-22',
        service: 'טיפוח',
      },
      {
        id: 'r16',
        authorName: 'אסף גורן',
        authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80',
        dogName: 'שניצל',
        rating: 5,
        text: 'שניצל הוא מלטז ורחל יודעת לטפל בפרווה שלו בצורה מושלמת. תמיד יוצא נקי ומסורק, ורחל ממש אוהבת אותו. שירות מעולה במחיר הוגן.',
        date: '2025-02-18',
        service: 'טיפוח',
      },
      {
        id: 'r17',
        authorName: 'חגית לוין',
        authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
        dogName: 'דובי',
        rating: 5,
        text: 'רחל טיפלה בדובי שהוא כלב גדול ומפחד ממקלחות. היא הייתה סבלנית ואדיבה וכבשה את לבו. יצא מגנד ומאושר. מומלצת מאוד!',
        date: '2025-01-25',
        service: 'טיפוח',
      },
      {
        id: 'r18',
        authorName: 'נילי ברק',
        authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
        dogName: 'פנדה',
        rating: 5,
        text: 'הסלון של רחל הוא הכי מקצועי שהכרתי. פנדה, הפינצ\'ר שלנו, תמיד יוצאת מושלמת. ריח נהדר, פרווה מבריקה. רחל שואלת לפני ועושה בדיוק מה שביקשתי.',
        date: '2024-12-12',
        service: 'טיפוח',
      },
      {
        id: 'r19',
        authorName: 'אמיר דהן',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        dogName: 'בוקסר',
        rating: 4,
        text: 'רחל מקצועית מאוד ואוהבת כלבים אמיתית. בוקסר תמיד יוצא נקי ומסופק. לפעמים צריך להמתין קצת אבל שווה כל רגע.',
        date: '2024-11-30',
        service: 'טיפוח',
      },
    ],
  },
  {
    id: 'danny-barak',
    name: 'דני ברק',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    city: 'תל אביב',
    neighborhood: 'צפון תל אביב',
    rating: 4.88,
    reviewCount: 156,
    pricePerNight: 160,
    services: ['boarding', 'sitting'],
    verified: true,
    responseTime: 'תוך שעה',
    repeatCustomers: 71,
    yearsExperience: 3,
    bio: 'היי, אני דני! גר בדירה גדולה בצפון תל אביב עם בן הזוג שלי. שנינו אוהבי כלבים שמחפשים להוסיף עוד קצת אהבה לחיים שלנו. אני עובד מהבית, מה שאומר שהכלב שלכם לא יישאר לבד אף רגע. אני מחויב לשמור על הרגלים ושגרת הכלב שלכם.',
    images: [
      'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=800&auto=format&fit=crop&q=80',
    ],
    dogSizes: ['tiny', 'small', 'medium'],
    homeEnvironment: ['דירה גדולה', 'עובד מהבית', 'ללא חיות מחמד', 'שכונה שקטה'],
    available: true,
    whatsapp: '972506789012',
    featured: false,
    distance: '0.8 ק"מ',
    reviews: [
      {
        id: 'r20',
        authorName: 'שיר טל',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        dogName: 'מגי',
        rating: 5,
        text: 'דני מדהים! מגי אהבה אותו מהרגע הראשון. עדכן אותנו כל הזמן עם תמונות מתוקות. הכלבה שלנו חזרה שמחה ורגועה. מומלץ מאוד!',
        date: '2025-03-05',
        service: 'לינה',
      },
      {
        id: 'r21',
        authorName: 'תמיר רוס',
        authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
        dogName: 'קאספר',
        rating: 5,
        text: 'דני עבד מהבית ולכן קאספר לא היה לבד אף רגע. הדירה שלו נקייה ומסודרת. קאספר גמל לדני באהבה בלתי מוגבלת. ממליץ!',
        date: '2025-02-10',
        service: 'לינה',
      },
      {
        id: 'r22',
        authorName: 'אדוה כהן',
        authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
        dogName: 'נאלה',
        rating: 4,
        text: 'חוויה טובה מאוד! נאלה הייתה אצל דני סוף שבוע שלם. דני אמין, אדיב ומקצועי. רק הייתי רוצה קצת יותר עדכונים בלילה.',
        date: '2025-01-20',
        service: 'שמירה',
      },
    ],
  },
  {
    id: 'sarit-friedman',
    name: 'שרית פרידמן',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    city: 'נתניה',
    neighborhood: 'נווה עמל',
    rating: 4.94,
    reviewCount: 98,
    pricePerNight: 85,
    services: ['walking', 'daycare', 'sitting'],
    verified: true,
    responseTime: 'תוך 30 דקות',
    repeatCustomers: 88,
    yearsExperience: 6,
    bio: 'שלום! אני שרית, גרה בנתניה עם הספניאל שלי, קפה. אני מאמינה שכל כלב מגיע לטיפול מלא באהבה. הטיולים שלי הם תמיד בפארקים ירוקים, 45 דקות לפחות, עם תשומת לב מלאה לכל כלב. מציעה גם מעון יום לכלבים קטנים ובינוניים.',
    images: [
      'https://images.unsplash.com/photo-1583511655826-05700d52f4d1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1534361960057-19f4c1e5be6f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1516734212722-37f5c00c5e9e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=800&auto=format&fit=crop&q=80',
    ],
    dogSizes: ['tiny', 'small', 'medium'],
    homeEnvironment: ['דירה עם מרפסת', 'ספניאל ביתי', 'קרוב לפארק', 'שכונה שקטה'],
    available: true,
    whatsapp: '972507890123',
    featured: false,
    distance: '28 ק"מ',
    reviews: [
      {
        id: 'r23',
        authorName: 'דפנה אור',
        authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
        dogName: 'ניקי',
        rating: 5,
        text: 'שרית היא שומרת מדהימה! ניקי ממש אוהבת אותה. תמיד מקבלים עדכונים ותמונות. הכלבה שלנו חוזרת מאושרת ומסופקת. ממליצה בחום!',
        date: '2025-03-12',
        service: 'מעון יום',
      },
      {
        id: 'r24',
        authorName: 'רועי שלום',
        authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
        dogName: 'טיגר',
        rating: 5,
        text: 'שרית מטיילת עם טיגר 3 פעמים בשבוע ואנחנו ממש מרוצים. מקצועית, אמינה ואוהבת כלבים. טיגר מחכה לה בהתרגשות בכל פעם.',
        date: '2025-02-05',
        service: 'טיול',
      },
      {
        id: 'r25',
        authorName: 'מיכל גל',
        authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
        dogName: 'ברוני',
        rating: 5,
        text: 'שרית טיפלה בברוני בזמן שהיינו בחופשה. היא שלחה תמונות כל יום ועדכנה אותנו על כל פרט קטן. חזרנו לכלב מאושר ובריא.',
        date: '2025-01-10',
        service: 'שמירה',
      },
    ],
  },
  {
    id: 'gil-shemesh',
    name: 'גיל שמש',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    city: 'ראשון לציון',
    neighborhood: 'נחלת יהודה',
    rating: 4.91,
    reviewCount: 74,
    pricePerNight: 170,
    services: ['boarding'],
    verified: true,
    responseTime: 'תוך שעתיים',
    repeatCustomers: 79,
    yearsExperience: 5,
    bio: 'שלום! אני גיל, גר בבית פרטי עם חצר בראשון לציון. יש לי ניסיון של 5 שנים בטיפול בכלבים ואני אוהב לתת לכל כלב תשומת לב מקסימלית. הבית שלי שקט, נוח ומושלם לכלבים שצריכים להרגיש בבית. מקבל עד 2 כלבים בו-זמנית.',
    images: [
      'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&auto=format&fit=crop&q=80',
    ],
    dogSizes: ['tiny', 'small', 'medium', 'large'],
    homeEnvironment: ['בית פרטי', 'חצר גדולה', 'ללא חיות מחמד', 'שכונה שקטה'],
    available: true,
    whatsapp: '972508901234',
    featured: false,
    distance: '12 ק"מ',
    reviews: [
      {
        id: 'r26',
        authorName: 'ורד אדרי',
        authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
        dogName: 'זאוס',
        rating: 5,
        text: 'גיל הוא שומר מעולה! זאוס הוא כלב גדול ופעיל וגיל ידע להתמודד אתו מצוין. שלח לנו תמונות כל יום והכלב חזר מאושר לגמרי.',
        date: '2025-03-08',
        service: 'לינה',
      },
      {
        id: 'r27',
        authorName: 'אלון ציפר',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        dogName: 'רינגו',
        rating: 5,
        text: 'חצר הבית של גיל היא חלום בשביל הכלב. רינגו ממש נהנה ורץ חופשי. גיל אחראי, נחמד ומקצועי. בהחלט נחזור!',
        date: '2025-02-01',
        service: 'לינה',
      },
      {
        id: 'r28',
        authorName: 'סוזן פריד',
        authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
        dogName: 'פלפל',
        rating: 4,
        text: 'גיל טיפל בפלפל סוף שבוע וחוויה טובה בסך הכל. הכלבה חזרה שמחה ובריאה. הייתי רוצה קצת יותר עדכונים אבל בסך הכל מרוצה.',
        date: '2025-01-05',
        service: 'לינה',
      },
    ],
  },
];

export function getProviderById(id: string): Provider | undefined {
  return PROVIDERS.find((p) => p.id === id);
}

export function getFeaturedProviders(): Provider[] {
  return PROVIDERS.filter((p) => p.featured);
}

export function getProvidersByService(service: ServiceType): Provider[] {
  return PROVIDERS.filter((p) => p.services.includes(service));
}
